apiVersion: v1
kind: Service
metadata:
  name: conductor
  namespace: conductor
spec:
  selector:
    app: conductor
  ports:
  - name: p2p
    port: 4001
    targetPort: 4001
  - name: grpc
    port: 50051
    targetPort: 50051
  - name: metrics
    port: 9090
    targetPort: 9090
  - name: rest
    port: 8080
    targetPort: 8080
  type: ClusterIP
