# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/conductor/conductor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'src/conductor/conductor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dsrc/conductor/conductor.proto\x12\tconductor\"8\n\x17SubmitEventBatchRequest\x12\r\n\x05\x65poch\x18\x01 \x01(\x05\x12\x0e\n\x06\x65vents\x18\x02 \x03(\t\"<\n\x18SubmitEventBatchResponse\x12\x10\n\x08\x62\x61tch_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\" \n\x0fGetBlockRequest\x12\r\n\x05\x65poch\x18\x01 \x01(\x05\"o\n\x10GetBlockResponse\x12\r\n\x05\x65poch\x18\x01 \x01(\x05\x12\x12\n\nblock_hash\x18\x02 \x01(\t\x12\x13\n\x0bmerkle_root\x18\x03 \x01(\t\x12\x0e\n\x06\x65vents\x18\x04 \x03(\t\x12\x13\n\x0bquorum_cert\x18\x05 \x01(\t\"!\n\x12GetDayProofRequest\x12\x0b\n\x03\x64\x61y\x18\x01 \x01(\x05\"e\n\x13GetDayProofResponse\x12\x12\n\nday_number\x18\x01 \x01(\x05\x12\x11\n\tvdf_proof\x18\x02 \x01(\t\x12\x12\n\ndifficulty\x18\x03 \x01(\x05\x12\x13\n\x0bquorum_cert\x18\x04 \x01(\t2\x82\x02\n\x10\x43onductorService\x12[\n\x10SubmitEventBatch\x12\".conductor.SubmitEventBatchRequest\x1a#.conductor.SubmitEventBatchResponse\x12\x43\n\x08GetBlock\x12\x1a.conductor.GetBlockRequest\x1a\x1b.conductor.GetBlockResponse\x12L\n\x0bGetDayProof\x12\x1d.conductor.GetDayProofRequest\x1a\x1e.conductor.GetDayProofResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.conductor.conductor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUBMITEVENTBATCHREQUEST']._serialized_start=44
  _globals['_SUBMITEVENTBATCHREQUEST']._serialized_end=100
  _globals['_SUBMITEVENTBATCHRESPONSE']._serialized_start=102
  _globals['_SUBMITEVENTBATCHRESPONSE']._serialized_end=162
  _globals['_GETBLOCKREQUEST']._serialized_start=164
  _globals['_GETBLOCKREQUEST']._serialized_end=196
  _globals['_GETBLOCKRESPONSE']._serialized_start=198
  _globals['_GETBLOCKRESPONSE']._serialized_end=309
  _globals['_GETDAYPROOFREQUEST']._serialized_start=311
  _globals['_GETDAYPROOFREQUEST']._serialized_end=344
  _globals['_GETDAYPROOFRESPONSE']._serialized_start=346
  _globals['_GETDAYPROOFRESPONSE']._serialized_end=447
  _globals['_CONDUCTORSERVICE']._serialized_start=450
  _globals['_CONDUCTORSERVICE']._serialized_end=708
# @@protoc_insertion_point(module_scope)
