# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.conductor import conductor_pb2 as src_dot_conductor_dot_conductor__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in src/conductor/conductor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConductorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitEventBatch = channel.unary_unary(
                '/conductor.ConductorService/SubmitEventBatch',
                request_serializer=src_dot_conductor_dot_conductor__pb2.SubmitEventBatchRequest.SerializeToString,
                response_deserializer=src_dot_conductor_dot_conductor__pb2.SubmitEventBatchResponse.FromString,
                _registered_method=True)
        self.GetBlock = channel.unary_unary(
                '/conductor.ConductorService/GetBlock',
                request_serializer=src_dot_conductor_dot_conductor__pb2.GetBlockRequest.SerializeToString,
                response_deserializer=src_dot_conductor_dot_conductor__pb2.GetBlockResponse.FromString,
                _registered_method=True)
        self.GetDayProof = channel.unary_unary(
                '/conductor.ConductorService/GetDayProof',
                request_serializer=src_dot_conductor_dot_conductor__pb2.GetDayProofRequest.SerializeToString,
                response_deserializer=src_dot_conductor_dot_conductor__pb2.GetDayProofResponse.FromString,
                _registered_method=True)


class ConductorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitEventBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDayProof(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConductorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitEventBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitEventBatch,
                    request_deserializer=src_dot_conductor_dot_conductor__pb2.SubmitEventBatchRequest.FromString,
                    response_serializer=src_dot_conductor_dot_conductor__pb2.SubmitEventBatchResponse.SerializeToString,
            ),
            'GetBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBlock,
                    request_deserializer=src_dot_conductor_dot_conductor__pb2.GetBlockRequest.FromString,
                    response_serializer=src_dot_conductor_dot_conductor__pb2.GetBlockResponse.SerializeToString,
            ),
            'GetDayProof': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDayProof,
                    request_deserializer=src_dot_conductor_dot_conductor__pb2.GetDayProofRequest.FromString,
                    response_serializer=src_dot_conductor_dot_conductor__pb2.GetDayProofResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'conductor.ConductorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('conductor.ConductorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConductorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitEventBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conductor.ConductorService/SubmitEventBatch',
            src_dot_conductor_dot_conductor__pb2.SubmitEventBatchRequest.SerializeToString,
            src_dot_conductor_dot_conductor__pb2.SubmitEventBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conductor.ConductorService/GetBlock',
            src_dot_conductor_dot_conductor__pb2.GetBlockRequest.SerializeToString,
            src_dot_conductor_dot_conductor__pb2.GetBlockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDayProof(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conductor.ConductorService/GetDayProof',
            src_dot_conductor_dot_conductor__pb2.GetDayProofRequest.SerializeToString,
            src_dot_conductor_dot_conductor__pb2.GetDayProofResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
